source 'https://rubygems.org'

gem 'bitters'
gem 'bourbon'
gem 'builder'
gem 'middleman'
gem 'middleman-autoprefixer'
gem 'middleman-blog'
gem 'middleman-deploy'
gem 'middleman-dotenv'
gem 'middleman-gh-pages'
gem 'middleman-imageoptim'
gem 'middleman-livereload'
gem 'middleman-minify-html'
gem 'middleman-syntax'
gem 'neat'
gem 'rake', '~> 12.3.3'
gem 'redcarpet'
